"""Typed domain contracts shared by GeoWeaver layers."""

from geoweaver.domain.enums import (
    ActivityPermissionStatus,
    BankSlopeClass,
    ConfidenceBand,
    GeometryType,
    HabitatFeature,
    PublicAccessState,
    RestrictionStatus,
    ShorelineType,
    SkillLevel,
    Substrate,
    TidalStatus,
    TideStage,
    VerificationState,
)
from geoweaver.domain.models import (
    AccessProfile,
    ConditionSnapshot,
    ConstraintResult,
    EnvironmentalProfile,
    GateCheck,
    Geometry,
    RankedRecommendation,
    RecommendationRun,
    Restriction,
    ScoreBreakdown,
    ShorelineSegment,
    TravelEstimate,
    UserPreferences,
)

__all__ = [
    "AccessProfile",
    "ActivityPermissionStatus",
    "BankSlopeClass",
    "ConditionSnapshot",
    "ConfidenceBand",
    "ConstraintResult",
    "EnvironmentalProfile",
    "GateCheck",
    "Geometry",
    "GeometryType",
    "HabitatFeature",
    "PublicAccessState",
    "RankedRecommendation",
    "RecommendationRun",
    "Restriction",
    "RestrictionStatus",
    "ScoreBreakdown",
    "ShorelineSegment",
    "ShorelineType",
    "SkillLevel",
    "Substrate",
    "TideStage",
    "TidalStatus",
    "TravelEstimate",
    "UserPreferences",
    "VerificationState",
]
